### ISSUE TITLE
Feature: Add Mica on Windows 10 version

### ISSUE THREAD

**Issue by DriftBR** [FireCubeStudios/DarkSky#11]
says it in the title

---

This should be possible using a library such as 10Mica by @ahmed605 which is also used inside the Mica™ app.

**Comment by FireCubeStudios** [comment]
So I added the library but it does not work??

**Comment by FireCubeStudios** [comment]
Mica has been added on Windows 10. Apparently 10Mica does not work in my secondary monitor so I thought it was bugged lmao

**Comment by ahmed605** [comment]
> Mica has been added on Windows 10. Apparently 10Mica does not work in my secondary monitor so I thought it was bugged lmao

@FireCubeStudios yeah, multi-monitor support isn't implemented yet
