### ISSUE TITLE
Improvement: Add login error reason

### ISSUE THREAD

**Issue by flyingdutch87** [FireCubeStudios/DarkSky#24]
Login using app password and bsky name does not work. Error: Failed to login session was null (ATProtoService LoginASync).
![darksky error 031224](https://github.com/user-attachments/assets/aa3b9f9b-6bd1-4917-ac7c-a0087f0bbecd)

---

**Failed to login session was null (ATProtoService LoginASync)**

**Comment by FireCubeStudios** [comment]
usually happens with wrong password and handle

**Comment by FireCubeStudios** [comment]
So next time I will show the reason for login failure

**Comment by FireCubeStudios** [comment]
![image](https://github.com/user-attachments/assets/0b98eacf-e673-4b17-a569-5896b2ae93ff)
so now in 0.3.8 the app will tell you why it failed, it could be due to wrong password like above or maybe some other very weird issue. Once the next update is released in the store if it does not fix the issue then pls send the new error message here

**Comment by flyingdutch87** [comment]
I have tried using my email and bsky password or the handle plus app password multiple times and it does not log me in. My password is correct as I can log in to ky account anywhere else using either method. Will try again with the newer build and report back

**Comment by FireCubeStudios** [comment]
So the update is now out in the store (0.3.8). Please try it out and let me know what happens

**Comment by FireCubeStudios** [comment]
@flyingdutch87 any update?

**Comment by flyingdutch87** [comment]
> @flyingdutch87 any update?

Yes: Seems it is the two-factor which the app is not compatible with, found the emails from bsky asking me to put in the two-factor code which darksky doesnt do

**Comment by FireCubeStudios** [comment]
0.4 or 0.5 will have a full login reform adding 2fa support among other features and it is being tracked in #22. So I will close this issue for now

**Comment by FireCubeStudios** [comment]
@flyingdutch87 0.4 is now in the store with 2FA support
