### ISSUE TITLE
Password field doesn't mask inputted text

### ISSUE THREAD

**Issue by SadLinusGuy0** [FireCubeStudios/DarkSky#25]
This can be a security risk, as peeping toms can see your full password in plain text. 

![image](https://github.com/user-attachments/assets/d79d9eb3-054f-4b78-918b-6134090f73f8)

**Comment by FireCubeStudios** [comment]
will be fixed in the next login reform

**Comment by FireCubeStudios** [comment]
v 0.3.8 has fixed this
