### ISSUE TITLE
Crashes on Xbox Series S

### ISSUE THREAD

**Issue by infinitepower18** [FireCubeStudios/DarkSky#30]
I downloaded the app on my Xbox Series S and was able to log in successfully, but upon loading the feed the app freezes and eventually crashes.

**Comment by FireCubeStudios** [comment]
Does the app work fine in PC loading the feed? 
Please try this out as it will help deduce whether the error is due to the xbox or maybe something in the feed like an unloadable post.

**Comment by infinitepower18** [comment]
It's fine on PC. It only crashes on my Xbox.

Was able to reproduce it every time by opening the app, going to notifications and attempting to scroll.

**Comment by infinitepower18** [comment]
@FireCubeStudios here's a video reproducing the crash

https://github.com/user-attachments/assets/f7de568c-b40f-4269-ad25-3f40d334862b

**Comment by infinitepower18** [comment]
@FireCubeStudios here's a video reproducing the crash

https://drive.google.com/file/d/1-5A1BZjyenMH5G7zDtDurTa0kyFGKv37/view?usp=sharing

**Comment by FireCubeStudios** [comment]
Interesting thanks, I will try to add more error handling to notifications page to see if that prevents it

**Comment by FireCubeStudios** [comment]
One important thing is I recently changed the backdrop of the app to be more vibrant, i have no idea if that even supports xbox so that will be another thing to check

**Comment by FireCubeStudios** [comment]
I added code that fixes the backdrop bug in 0.4.11

**Comment by FireCubeStudios** [comment]
0.4.12.0 is out now so can you try it to see if it works @infinitepower18

**Comment by infinitepower18** [comment]
The crash is resolved but now I'm seeing red error messages for a few seconds when opening it #37
