### ISSUE TITLE
Bug: Cannot login without 2FA

### ISSUE THREAD

**Issue by magicuk** [FireCubeStudios/DarkSky#31]
Can not use app even with correct password, as it is asking for 2factor code? No where to put 2factor code on app login so cant login.

**Comment by FireCubeStudios** [comment]
2FA i snot supported yet but I am working on towards adding it

**Comment by drasticactions** [comment]
You need to use an App Password created from the [bsky.app](https://bsky.app). AFAIK There is no 2FA Email/Phone support for password authentication in ATProtocol itself, only on the Bluesky app. So it goes beyond the bounds of what's possible in a third-party client. The solution in ATprotocol would be to use OAuth for that instead.

@FireCubeStudios IMO I would close this issue, there's no fix for this.

**Comment by FireCubeStudios** [comment]
> You need to use an App Password created from the [bsky.app](https://bsky.app). AFAIK There is no 2FA Email/Phone support for password authentication in ATProtocol itself, only on the Bluesky app. So it goes beyond the bounds of what's possible in a third-party client. The solution in ATprotocol would be to use OAuth for that instead.
> 
> 
> 
> @FireCubeStudios IMO I would close this issue, there's no fix for this.

What about the AuthFactoToken parameter in  https://docs.bsky.app/docs/api/com-atproto-server-create-session

**Comment by drasticactions** [comment]
Ah, I didn’t know that existed.

that would probably do it. IMO I would still enforce using app passwords instead (or use OAuth), since that’s what they were designed for, but it’s up to you.

**Comment by magicuk** [comment]
As it happens, the bsky app password way does indeed, work. However, adding the 2factor would maybe be bennifical to users for security reasurance.

**Comment by FireCubeStudios** [comment]
#22 is a checklist for the next login refactor in v 0.4 or 0.5. So I will track this there

**Comment by FireCubeStudios** [comment]
@magicuk 0.4 is now in the store with 2FA support

**Comment by magicuk** [comment]
That was a very quick turn around! I'm currently away atm, but will endeavour to check this out. Thanks once again!
