### ISSUE TITLE
Bug: Errors that should be suppressed are not

### ISSUE THREAD

**Issue by infinitepower18** [FireCubeStudios/DarkSky#37]
Getting one of these error messages when opening the app on both the PC and Xbox versions:

<img width="902" alt="image" src="https://github.com/user-attachments/assets/33608f57-8d36-40fd-b570-c64b04b9ac6c" />

![Xbox 20_12_2024 6_29_37 PM](https://github.com/user-attachments/assets/56d7046f-7b8d-42eb-8997-7fd35aed4ae2)

**Comment by FireCubeStudios** [comment]
Yup this is known, i am pushing a temporary fix for 0.4.13.0

**Comment by FireCubeStudios** [comment]
So sometimes "errors" happen which don't actually do anything to affect the rest of the app, thats why for 0.4.13.0 I am adding a seperate error UI for all errors, non serious and serious ones 
![image](https://github.com/user-attachments/assets/2985741b-65d3-42f4-bdf0-62ad221ab6b5)

**Comment by FireCubeStudios** [comment]
0.4.16.0 has fixed this
