### ISSUE TITLE
Bug: Altered backdrop material does not work well on light mode

### ISSUE THREAD

**Issue by sixunity** [FireCubeStudios/DarkSky#40]
The app seems to use a different implementation of mica or something, its way more transparent than the default one, which results in it looking broken and hard to read 
![image](https://github.com/user-attachments/assets/9dc1dae4-453b-4d0c-a984-5a24fffea31a)

settings app background for comparison

![image](https://github.com/user-attachments/assets/7e052804-5a95-4d07-b57e-666941806c25)

**Comment by Lamparter** [comment]
UI tests needed
Though I only know how to do for WinUI3 apps and not UWP

**Comment by FireCubeStudios** [comment]
For light mode I could make it switch to use the default Mica

**Comment by FireCubeStudios** [comment]
![image](https://github.com/user-attachments/assets/7a62c819-9b72-49fb-b414-3f71971588fb)
figured it out, in lightmode it still renders the darkmode version lmao

**Comment by FireCubeStudios** [comment]
ok fixed, will release in next version, its also theme aware now
