### ISSUE TITLE
Spec: .NET 9 NativeAOT shipping progress

### ISSUE THREAD

**Issue by Lamparter** [FireCubeStudios/DarkSky#42]
The app should be ported to .NET 9 on UWP. A test app called WarElephant has been created to attempt this, and there is an ongoing discussion in UWPC about porting the app and fixing #29 in the process.

**Comment by FireCubeStudios** [comment]
WatElephant

**Comment by Lamparter** [comment]
aaa

**Comment by FireCubeStudios** [comment]
Lets use the old issue to track .net 9 as it also will remind to test arm64
